[theme]
primaryColor = "#FC3D21"
backgroundColor = "#0B1D3A"
secondaryBackgroundColor = "#326A8E"
textColor = "#ffffff"
font = "sans serif"

# Used to prevent torch errors
[server]
runOnSave = false

